#! bash
#Script to strip data from a period summary file and get into format for gnuplot

# Usage: strip.sh infile outfile

# infile is the period summary file generated by my battery monitor program
# period could be hour, day, month or year
# outfile is file to output the gnuplot ready data

# The first command strips out datestamp and the 'power' information
# The second command amagamates the datestamp and the 'power' information
# The third command strips out the 2017 data
# The forth command removes all the delimiters from the lines
# The last command cuts the timestamp down to year,month and day and saves the file

sed -n -e '/'timestamp'/p'  -e "/'power'/p" $1 | \
paste -d ' ' - - | \
sed -n "/'2017/p" | \
sed  -e "s/('timestamp',..'//" -e  "s/'.).*('power',.'[[]//" -e "s/,//g" -e "s/[]]')//" | \
sed 's/\(2017....\)....../\1/' > $2
